name: Build Ariel Moodle Bot Docker Image

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build ariel-moodle-bot
      run: docker build -t ariel-moodle-bot .
